apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-app-ingress
  namespace: bookstore
spec:
  ingressClassName: nginx
  rules:
    - host: bookstore.com
      http:
        paths:
          - path: /
            backend:
             service:
               name: bookstore-app-service
               port:
                 number: 80
            pathType: Prefix