apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  namespace: bookstore
type: Opaque
data:
  # base64 Bookstore secrets
  # cmd command echo -n "secret-value" | base64
  book-store-name: Qm9va3N0b3JlIHNlY3JldHM=