apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bookstore-deployment
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: bookstore-app-container
          # Will generally get this from a private image repo like ECR (Amazon Elastic Container Registry)
          image: euznsazzad/sazzad-kubernetes-demo:1.0.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              # This specifies the minimum CPU request, set to 30 millicores (m).
              # This means the container needs at least 30/1000 of a CPU core (roughly 3% of a single core).
              cpu: 250m
              # This specifies the minimum memory request, set to 65 Megabytes (Mi).
              memory: 500Mi
            limits:
              cpu: 350m
              memory: 600Mi
          securityContext:
            runAsNonRoot: false
          env:
            - name: BOOK_STORE_NAME
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: book-store-name
